language: node_js
node_js:
  - stable

services:
  - docker

before_install:
  - docker pull apisguru/graphql-faker
  - docker run -v=${PWD}:/workdir -p=9002:9002 apisguru/graphql-faker test/data/schema.sdl

notifications:
  email:
    - damon.oehlman@gmail.com
